[
  {
    id: 1,
    item_author: "Retro",
    item_title: "BMW M3 E30",
    item_topic: "Drift RC Car",
    item_description:
      "Experience high-speed drifting in seconds as everything is included such as battery and charger. Perfect for running multiple cars simultaneously with friends. The detailed retro-drift body shell and spoke wheels give it a classic look, while front LED lights illuminate your way as you zoom drift your way in the dark.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/img1.jpg",
    thumbnail_image_location: "image/img1.jpg",
    thumbnail_content_title: "BMW M3 E30",
    thumbnail_description: "Drift RC Car",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 2,
    item_author: "Traxxas",
    item_title: "Trail Trucks",
    item_topic: "TRX-4 & TRX-4M",
    item_description:
      "The Traxxas TRX-4 and TRX-4m are two formidable tucks that define two categories of RC Rock Crawling, Standard and Mini. Traxxas introduced the 1/10 TRX-4 in 2017 with the iconic Land Rover body. Now, Traxxas has over 20 variations of TRX-4 and a whole line of mini, 1/18 TRX-4m models. Explore this article and find the perfect TRX-4/TRX-4m for you!",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/trx4m.jpg",
    thumbnail_image_location: "image/trx4m.jpg",
    thumbnail_content_title: "Trail Trucks",
    thumbnail_description: "TRX-4 & TRX-4M",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 3,
    item_author: "FMS",
    item_title: "Land Rover",
    item_topic: "Camel Trophy Edition RTR",
    item_description:
      "The Camel Trophy was a vehicle-oriented adventure event held between 1980 and 2000. Unlike typical races, its focus wasn't on speed but on testing the endurance of participants and vehicles in extreme conditions. Emphasizing teamwork and resilience, it earned the nickname 'The Olympics of 4x4.' As the core sponsor, Land Rover featured vehicles like the Range Rover, Defender 90, Defender 110, and Discovery. These iconic Land Rovers, painted in distinctive yellow sand, navigated some of the world's most challenging terrains, creating legendary off-road stories. Let's revive the Camel Trophy spirit with the FCX24M Land Rover!",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/img2.jpg",
    thumbnail_image_location: "image/img2.jpg",
    thumbnail_content_title: "Land Rover",
    thumbnail_description: "Camel Trophy Edition RTR",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 4,
    item_author: "FMS",
    item_title: "Land Cruiser",
    item_topic: "V2 Toyota LC 80 RTR",
    item_description:
      "New Licensed LC80 RC Crawler. The Land Cruiser 80, an off-roading legend, and FMS’s 1/18 LC80 V2 RC Rock Crawler have been cherished by RC enthusiasts. In 2023, with Toyota’s authorization once again, FMS presents an upgraded LC80 rc rock crawler 4×4, featuring the new FCX18 chassis. Enhanced exteriors, and an even better off-road experience are in store. FMS’s commitment to detail perfection makes this 4WD rock crawler the top pick for RC off-road enthusiasts!",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/img3.jpg",
    thumbnail_image_location: "image/img3.jpg",
    thumbnail_content_title: "Toyota Land Cruiser",
    thumbnail_description: "V2 Toyota Land Cruiser 80 RTR",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 5,
    item_author: "FMS",
    item_title: "Land Cruiser",
    item_topic: "V2 Toyota LC 80 RTR",
    item_description:
      "New Licensed LC80 RC Crawler. The Land Cruiser 80, an off-roading legend, and FMS’s 1/18 LC80 V2 RC Rock Crawler have been cherished by RC enthusiasts. In 2023, with Toyota’s authorization once again, FMS presents an upgraded LC80 rc rock crawler 4×4, featuring the new FCX18 chassis. Enhanced exteriors, and an even better off-road experience are in store. FMS’s commitment to detail perfection makes this 4WD rock crawler the top pick for RC off-road enthusiasts!",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/img4.jpg",
    thumbnail_image_location: "image/img4.jpg",
    thumbnail_content_title: "Toyota Land Cruiser",
    thumbnail_description: "V2 Toyota Land Cruiser 80 RTR",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 6,
    item_author: "Traxxas",
    item_title: "Traxxas X-maxx",
    item_topic: "Rock and Roll",
    item_description:
      "The Traxxas X-Maxx 8S 4WD Brushless RTR Monster Truck brings the same unrelenting 4X4 power, mammoth size and award-winning innovation to the game that make X-Maxx the ultimate monster truck. When you add 30+ volts of extreme 8s power, X-Maxx 8S defies physics, unleashing jaw-dropping acceleration and 50+mph speeds. Engineered to conquer the most extreme terrain and take brutal real-world punishment in stride, X-Maxx is the definition of Traxxas Tough™.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/traxxas-xmax.jpg",
    thumbnail_image_location: "image/traxxas-xmax.jpg",
    thumbnail_content_title: "",
    thumbnail_description: "",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 7,
    item_author: "HB Toys",
    item_title: "APEX4 RTR",
    item_topic: "R1601",
    item_description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat, veritatis consequatur. Beatae consequatur veritatis earum quam pariatur voluptatibus quisquam architecto voluptas officia expedita explicabo velit, voluptatum harum dolore fugit? Odio.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/hb-toys-16-defender.jpg",
    thumbnail_image_location: "image/hb-toys-16-defender.jpg",
    thumbnail_content_title: "",
    thumbnail_description: "",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 8,
    item_author: "CXD",
    item_title: "CDX Mini",
    item_topic: "CXD D12",
    item_description:
      "True 1/16 scale. Actual car is very small. Color: White(Creamy). Proportional Steering and Throttle. 1s 14500 500mAh powered. 2.4Ghz Radio. Multiple users can play the same model at the same time. Product dimension of 11.5cm x 10.5cm x 21cm. Wheelbase 120mm~. 130 motor (rated at 23000rpm at 3.7V). Working suspension. Realistic chassis. Low voltage & over current protection. Plastic ball join at steering knuckle. Working headlight. Rubber tires.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/cxd-d12-mini.jpg",
    thumbnail_image_location: "image/cxd-d12-mini.jpg",
    thumbnail_content_title: "CXD Mini",
    thumbnail_description: "CXD D12",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 9,
    item_author: "Bebbly",
    item_title: "G550 4X4 Metal",
    item_topic: "Diecast Car",
    item_description:
      "The doors and the hood can be opened; And the press of lots of parts can make the car sound; Both the front and rear of the car are equipped with high brightness LED lights, just like a real super car, pull back to work, easy to operate, don't worry about it not working; Speed is not fast enough to prevent a child from falling.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/brabus-gwagon.jpg",
    thumbnail_image_location: "image/brabus-gwagon.jpg",
    thumbnail_content_title: "Bebbly",
    thumbnail_description: "Diecast Car",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 10,
    item_author: "FMS",
    item_title: "Rock Crawler",
    item_topic: "Army Military",
    item_description:
      "Superior Off-Road Performance: Built with a modern stepped chassis and hydraulic shock absorbers, this model offers unbeatable traction and stability on any terrain. It replicates the original’s steel plate springs but with an enhanced oil shock system for maximum axle flex.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/willys-fms.jpg",
    thumbnail_image_location: "image/willys-fms.jpg",
    thumbnail_content_title: "Army Military Truck",
    thumbnail_description: "Rock Crawler",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 11,
    item_author: "HB Toys",
    item_title: "Defender",
    item_topic: "RC Offroad",
    item_description: "HB Toys ZP1005 1/10 Scale 4WD RC Off-Road Car",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/defender.png",
    thumbnail_image_location: "image/defender.png",
    thumbnail_content_title: "Defender",
    thumbnail_description: "RC Offroad",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
  {
    id: 12,
    item_author: "WLTOYS",
    item_title: "Rock Crawler",
    item_topic: "4WD Off-Road RC",
    item_description:
      "WLTOYS 104020 1/10 Scale Electric RC 4WD Rock Crawler is designed for both beginners and seasoned RC enthusiasts. This high-performance RC car offers a robust and realistic driving experience.",
    item_insta_link: "https://www.instagram.com/rcanddiecast/",
    item_yt_link: "https://youtube.com/@ebinumer_stories?si=v59mSfK0dBrOEJha",
    item_image_location: "image/bronco-wl-toys.jpg",
    thumbnail_image_location: "image/bronco-wl-toys.jpg",
    thumbnail_content_title: "Rock Crawler",
    thumbnail_description: "4WD Off-Road RC",
    button_order_class: "order-buttons",
    button_video_class: "review-buttons",
  },
];
